//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//       如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="SaleOrderInfoRepository.cs">
//        Copyright(c)2013 GMFCN.All rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：yxd
//        生成时间：2020-02-21 16:20
// </copyright>
//------------------------------------------------------------------------------
using WebApi.IRepository;
using FXKJ.Infrastructure.Dapper;
using EntitiesModels.DtoModels;
using EntitiesModels.QueryModels;
using System.Collections.Generic;
using System.Data;
using FXKJ.Infrastructure.Auth;
using FXKJ.Infrastructure.Auth.Auth;

namespace WebApi.Repository
{
    /// <summary>
    ///   数据访问层——SaleOrderInfo
    /// </summary>
    public partial class SaleOrderInfoRepository : ISaleOrderInfoRepository
    {

        private readonly AuthInfoViewModel authInfo = FormAuthenticationExtension.CurrentAuth();
        private string permissionWhere
        {
            get
            {
                if (authInfo.Roles.Contains("admin"))
                {
                    return string.Format(" where 1=1 ");
                }
                else
                {
                    return string.Format(" where a.P_MerchantNo={0} ", authInfo.MerchantNo);
                }
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="pOrderNum"></param>
        /// <returns></returns>
        public IEnumerable<SaleOrderInfoViewModel> GetSaleOrderInfoViewModelList(string pOrderNum)
        {
            var sql = @" select * from (
SELECT 
a.*,
b.ProductName,
b.SimpleCode
 FROM [dbo].[SaleOrderInfo] AS a WITH (NOLOCK)
LEFT JOIN [dbo].[Product] AS b WITH (NOLOCK)
ON a.SProductCode=b.ProductCode
WHERE a.sOrderNum='" + pOrderNum + "' ) as a "+permissionWhere+" ";

            var list =  SqlMapperUtil.GetListData<SaleOrderInfoViewModel>(sql);
            return list;
        }

        public DataTable GetSaleOrderInfoViewModelDataTable(QueryModel model)
        {
            var sql = @" select * from ( SELECT  
a.SOrderNum ,
g.NickName,
a.PhoneNumber,
a.SOrderCreateTime,
a.AllSaleAmount,
a.AllSaleFreightAmount,
a.AllSaleSettlementAmount,
a.AllSaleSumAmount,
(case when a.SaleOrderState='FF01' then '未完成' else '已锁定' end) as SaleOrderState,
d.ExpressNumber,
d.SaleFreightAmount,
e.ProductCode,
e.ProductName,
e.SimpleCode,
f.CategoryName,
f.CategoryCode,
d.SaleCount,
d.SalePrice,
d.SaleAmount,
d.SaleSumAmount,
d.SaleSettlementAmount,
case when d.SaleOrderInfoState='SS01' then '未发货'  
when  d.SaleOrderInfoState='SS02' then '已发货'
when d.SaleOrderInfoState='SS03' then '已签收'
else  '已丢失' end as SaleOrderInfoState
 FROM [dbo].[SaleOrder] AS a WITH(NOLOCK) 
left join [dbo].[SaleOrderInfo] AS d WITH(NOLOCK)  on a.SOrderNum=d.SOrderNum
left join [dbo].[Product] AS e WITH (NOLOCK) ON d.SProductCode=e.ProductCode
left join [dbo].[Category] AS f WITH (NOLOCK) ON f.CategoryCode=e.CategoryCode
left join dbo.[UserInfo] as g with (nolock) on a.PhoneNumber=g.PhoneNumber "+permissionWhere+") as cc @where  ";
            return SqlMapperUtil.GetDataTable(sql, model);
        }
    }
}

