//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//       如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="IDataBackupBLL.cs">
//        Copyright(c)2013 GMFCN.All rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：yxd
//        生成时间：2020-04-24 14:10
// </copyright>
//------------------------------------------------------------------------------
using EntitiesModels.Models;
using EntitiesModels.Models.SysModels;
using EntitiesModels.HttpResponse;
using EntitiesModels.QueryModels;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using EntitiesModels.DtoModels;

namespace WebApi.IBLL
{
    /// <summary>
    ///   业务层接口——DataBackup
    /// </summary>
    public partial interface IDataBackupBLL
    {
        /// <summary>
        /// 数据备份
        /// </summary>
        /// <param name="dataBackup"></param>
        /// <returns></returns>
        HttpReponseModel<DataBackup> DataBaseBackup(DataBackup dataBackup);

        /// <summary>
        /// 数据库列表
        /// </summary>
        /// <returns></returns>
        HttpReponseModel<List<SelectViewModel>> GetSelectViewModelList();

        /// <summary>
        /// 获取备份数据库路径
        /// </summary>
        /// <returns></returns>
        HttpReponseModel<string> GetDBDefaultPath();

        /// <summary>
        /// 数据还原
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        HttpReponseModel<string> DestoreData(int id);

    }
}

