//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//       如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="PurchaseOrderInfoBLL.cs">
//        Copyright(c)2013 GMFCN.All rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：yxd
//        生成时间：2020-02-04 15:45
// </copyright>
//------------------------------------------------------------------------------
using EntitiesModels.Models;
using FXKJ.Infrastructure.Logic;
using WebApi.IRepository;
using WebApi.IBLL;
using FXKJ.Infrastructure.Entities.QueryModel;
using System.Threading.Tasks;
using EntitiesModels.DtoModels;
using FXKJ.Infrastructure.Entities.HttpResponse;
using FXKJ.Infrastructure.DataAccess;
using System.Collections.Generic;
using System;
using System.Transactions;
using FXKJ.Infrastructure.Entities.Enum;
using FXKJ.Infrastructure.Core.Extensions;

namespace WebApi.BLL
{
    /// <summary>
    ///   业务访问——PurchaseOrderInfo
    /// </summary>
    public partial class PurchaseOrderInfoBLL : IPurchaseOrderInfoBLL
    {

        /// <summary>
        /// 构造函数依赖注入
        /// </summary>
        private readonly IPurchaseOrderInfoRepository _purchaseOrderInfoRepository;
       
       /// <summary>
       /// 
       /// </summary>
       /// <param name="purchaseOrderInfoRepository"></param>
       /// <param name="logic"></param>
        public PurchaseOrderInfoBLL(
            IPurchaseOrderInfoRepository purchaseOrderInfoRepository,
            ILogic<PurchaseOrderInfo> logic) 
            : this(logic)
        {
            _purchaseOrderInfoRepository = purchaseOrderInfoRepository;
        }

       /// <summary>
       /// 
       /// </summary>
       /// <param name="orderNumber"></param>
       /// <returns></returns>
        public HttpReponseModel<List<PurchaseOrderInfoViewModel>> GetPurchaseOrderInfoViewModelList(string orderNumber)
        {
            HttpReponseModel<List<PurchaseOrderInfoViewModel>> httpReponse = new HttpReponseModel<List<PurchaseOrderInfoViewModel>>();
            httpReponse.Data = _purchaseOrderInfoRepository.GetPurchaseOrderInfoViewModelList(orderNumber) as List<PurchaseOrderInfoViewModel>;
            return httpReponse;
        }
    }
}

