//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//       如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="RoleBLL.cs">
//        Copyright(c)2013 GMFCN.All rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：yxd
//        生成时间：2020-03-20 17:04
// </copyright>
//------------------------------------------------------------------------------
using EntitiesModels.Models;
using EntitiesModels.Models.SysModels;
using FXKJ.Infrastructure.Logic;
using WebApi.IRepository;
using WebApi.IBLL;
using FXKJ.Infrastructure.Entities.HttpResponse;
using FXKJ.Infrastructure.Entities.QueryModel;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Linq;
using System.Threading.Tasks;
using FXKJ.Infrastructure.DataAccess;
using FXKJ.Infrastructure.Entities.Enum;

namespace WebApi.BLL
{
    /// <summary>
    ///   业务访问——Role
    /// </summary>
    public partial class RoleBLL : IRoleBLL
    {

        private readonly IEFRepository<RoleMenu> _roleMenuEFRepository;
        private readonly IEFRepository<MerchantRole> _merchantRoleEFRepository;
        public RoleBLL(IEFRepository<MerchantRole> merchantRoleEFRepository, IEFRepository<RoleMenu> roleMenuEFRepository, ILogic<Role> logic) : this(logic)
        {
            _roleMenuEFRepository = roleMenuEFRepository;
            _merchantRoleEFRepository = merchantRoleEFRepository;
        }

        public HttpReponseModel<bool> GetIsDeleteFlag(string roleCode)
        {
            HttpReponseModel<bool> httpReponse = new HttpReponseModel<bool>();
            var list1 = _roleMenuEFRepository.GetList(p => p.RoleCode == roleCode);
            var list2 = _merchantRoleEFRepository.GetList(p => p.RoleCode == roleCode);
            if (list1.Count() > 0 && list2.Count() == 0)
            {
                httpReponse.Data = false;
                httpReponse.ResultSign = ResultSign.Warning;
                httpReponse.Message = "先解除已配置菜单在删除角色！";
            }
            else if (list1.Count() == 0 && list2.Count() > 0)
            {
                httpReponse.Data = false;
                httpReponse.ResultSign = ResultSign.Warning;
                httpReponse.Message = "先解除已配置商户在删除角色！";
            }
            else if (list1.Count() > 0 && list2.Count() > 0)
            {
                httpReponse.Data = false;
                httpReponse.ResultSign = ResultSign.Warning;
                httpReponse.Message = "先解除已配置商户和菜单在删除角色！";
            }
            else
            {
                httpReponse.Data = true;
                httpReponse.ResultSign = ResultSign.Successful;
                httpReponse.Message = "操作成功！";
            }
            return httpReponse;
        }
    }
}

