//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//       如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// 
//        Copyright(c)2013 GMFCN.All rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：yxd
//        生成时间：2020-01-02 00:50
// </copyright>
//------------------------------------------------------------------------------
using EntitiesModels.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace EntitiesModels
{
    public class MyContext : DbContext
    {
  
      public MyContext() : base("name=MyStrConn")
        {
                   
        }
        
                /// <summary>
       ///   Business
      /// </summary>
       public DbSet<Business> Business { get; set; }

               /// <summary>
       ///   Prodoct
      /// </summary>
       public DbSet<Prodoct> Prodoct { get; set; }

               /// <summary>
       ///   ProductType
      /// </summary>
       public DbSet<ProductType> ProductType { get; set; }

               /// <summary>
       ///   PurchaseOrder
      /// </summary>
       public DbSet<PurchaseOrder> PurchaseOrder { get; set; }

               /// <summary>
       ///   PurchaseOrderInfo
      /// </summary>
       public DbSet<PurchaseOrderInfo> PurchaseOrderInfo { get; set; }

               /// <summary>
       ///   SaleOrder
      /// </summary>
       public DbSet<SaleOrder> SaleOrder { get; set; }

               /// <summary>
       ///   SaleOrderInfo
      /// </summary>
       public DbSet<SaleOrderInfo> SaleOrderInfo { get; set; }

               /// <summary>
       ///   TransferBin
      /// </summary>
       public DbSet<TransferBin> TransferBin { get; set; }

          }
}

